server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fisglobal
    username: root
    password: root
  application:
    name: comments-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8080/eureka-service
      
